version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3305:3306"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=test
      - DB_USERNAME=root
      - DB_PASSWORD=test
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - "4000:4000"
    command:
      - bash
      - -c
      - |
        /app/wait-for-it.sh db:3306 -t 10
        npm run local
    volumes:
      - ./:/app/

volumes:
  db_data: